### ISSUE TITLE
Make ER diagram 

### ISSUE THREAD

**Issue by WillMarcuss** [WillMarcuss/Health-and-Fitness-Club-Management-System#2]
Explain the conceptual design of the database: the ER-diagram for the Health and Fitness Club, and assumptions
made regarding cardinalities and participation types. Ensure that assumptions align with the problem statement.

**Comment by WillMarcuss** [comment]
We will all create the diagram together on a share screen or shared drawing board

**Comment by WillMarcuss** [comment]
Here is the link to the ER diagram in draw io: [https://drive.google.com/file/d/1dutyNBxMLJA_4R1Ydi3VpQd-HerCnvJi/view?usp=share_link](url)

**Comment by WillMarcuss** [comment]
Here is the project notes Google doc: https://docs.google.com/document/d/1nsYeua-yon9dyq6_K0Iap7-I9pwcjNSrECr9iYYvPxM/edit

**Comment by JoshuaSaikali** [comment]
This task has been completed
